steps:
  # Build the Docker image from the Dockerfile in the repository
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-app:$SHORT_SHA', '.']

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-app:$SHORT_SHA']

# Specify the Google Cloud Storage bucket for storing build logs
logsBucket: 'gs://bookdemologbucket'

# Specify the images that will be available after the build
images:
  - 'gcr.io/$PROJECT_ID/my-app:$SHORT_SHA'

# Optionally, set a timeout for the build
timeout: '1200s'  # Example: 20 minutes

# If using a custom service account, specify it here
# serviceAccount: 'projects/YOUR_PROJECT_ID/serviceAccounts/YOUR_SERVICE_ACCOUNT_EMAIL'
