server:
  error:
    include-binding-errors: always
    include-message: always
booksDemo:
  titleToAuthorMapperServiceUrl: https://dummyjson.com/
  enableAutoAuthorMapping: true

twillio:
  accountSid: abc
  authToken: def

